{% set name = "qhub" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: dd42e40dc7bdc9ee8b52c2a18d83884e74af0a88467f8fca6a950b9ca44514d4

build:
  number: 1
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }},<4.0
    - auth0-python
    - bcrypt
    - boto3
    - cloudflare
    - gitignore-parser ==0.0.8
    - pydantic
    - pynacl
    - python-keycloak
    - python-kubernetes
    - ruamel.yaml
    - azure-identity ==1.6.1
    - azure-mgmt-containerservice ==16.2.0
    - importlib_metadata
    - rich
    - requests-toolbelt <0.10.0,>=0.9.1
    - typer
    - questionary

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
    - if [[ $(qhub --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - tylerpotts
    - costrouc
    - danlester
    - aktech
    - viniciusdc
    - iameskild
